export { MainPage } from "./MainPage";
export { PostsPage } from "./PostsPage";
export { AuthPage } from "./AuthPage";
export { AboutPage } from "./AboutPage";
export { ProfilePage } from "./ProfilePage";
export { Followers } from "./Followers";
export { Following } from "./Following";
export { SearchPage } from "./SearchPage";
export { CreatePostPage } from "./CreatePostPage";
