/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuestRouteImport } from './routes/_quest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as QuestAuthRouteImport } from './routes/_quest/auth'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as AuthLayoutIndexRouteImport } from './routes/_auth/_layout/index'
import { Route as AuthPostsPostIdRouteImport } from './routes/_auth/posts/$postId'
import { Route as AuthLayoutSettingsRouteImport } from './routes/_auth/_layout/settings'
import { Route as AuthLayoutSearchRouteImport } from './routes/_auth/_layout/search'
import { Route as AuthLayoutCreate_postRouteImport } from './routes/_auth/_layout/create_post'
import { Route as AuthLayoutProfileIndexRouteImport } from './routes/_auth/_layout/profile/index'
import { Route as AuthLayoutProfileUserIdIndexRouteImport } from './routes/_auth/_layout/profile/$userId.index'
import { Route as AuthLayoutProfileUserIdFollowingRouteImport } from './routes/_auth/_layout/profile/$userId.following'
import { Route as AuthLayoutProfileUserIdFollowersRouteImport } from './routes/_auth/_layout/profile/$userId.followers'

const QuestRoute = QuestRouteImport.update({
  id: '/_quest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestAuthRoute = QuestAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => QuestRoute,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutIndexRoute = AuthLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthPostsPostIdRoute = AuthPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLayoutSettingsRoute = AuthLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSearchRoute = AuthLayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutCreate_postRoute = AuthLayoutCreate_postRouteImport.update({
  id: '/create_post',
  path: '/create_post',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutProfileIndexRoute = AuthLayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutProfileUserIdIndexRoute =
  AuthLayoutProfileUserIdIndexRouteImport.update({
    id: '/profile/$userId/',
    path: '/profile/$userId/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutProfileUserIdFollowingRoute =
  AuthLayoutProfileUserIdFollowingRouteImport.update({
    id: '/profile/$userId/following',
    path: '/profile/$userId/following',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutProfileUserIdFollowersRoute =
  AuthLayoutProfileUserIdFollowersRouteImport.update({
    id: '/profile/$userId/followers',
    path: '/profile/$userId/followers',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof QuestAuthRoute
  '/create_post': typeof AuthLayoutCreate_postRoute
  '/search': typeof AuthLayoutSearchRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/posts/$postId': typeof AuthPostsPostIdRoute
  '/': typeof AuthLayoutIndexRoute
  '/profile': typeof AuthLayoutProfileIndexRoute
  '/profile/$userId/followers': typeof AuthLayoutProfileUserIdFollowersRoute
  '/profile/$userId/following': typeof AuthLayoutProfileUserIdFollowingRoute
  '/profile/$userId': typeof AuthLayoutProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof QuestAuthRoute
  '/create_post': typeof AuthLayoutCreate_postRoute
  '/search': typeof AuthLayoutSearchRoute
  '/settings': typeof AuthLayoutSettingsRoute
  '/posts/$postId': typeof AuthPostsPostIdRoute
  '/': typeof AuthLayoutIndexRoute
  '/profile': typeof AuthLayoutProfileIndexRoute
  '/profile/$userId/followers': typeof AuthLayoutProfileUserIdFollowersRoute
  '/profile/$userId/following': typeof AuthLayoutProfileUserIdFollowingRoute
  '/profile/$userId': typeof AuthLayoutProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_quest': typeof QuestRouteWithChildren
  '/_auth/_layout': typeof AuthLayoutRouteWithChildren
  '/_quest/auth': typeof QuestAuthRoute
  '/_auth/_layout/create_post': typeof AuthLayoutCreate_postRoute
  '/_auth/_layout/search': typeof AuthLayoutSearchRoute
  '/_auth/_layout/settings': typeof AuthLayoutSettingsRoute
  '/_auth/posts/$postId': typeof AuthPostsPostIdRoute
  '/_auth/_layout/': typeof AuthLayoutIndexRoute
  '/_auth/_layout/profile/': typeof AuthLayoutProfileIndexRoute
  '/_auth/_layout/profile/$userId/followers': typeof AuthLayoutProfileUserIdFollowersRoute
  '/_auth/_layout/profile/$userId/following': typeof AuthLayoutProfileUserIdFollowingRoute
  '/_auth/_layout/profile/$userId/': typeof AuthLayoutProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/create_post'
    | '/search'
    | '/settings'
    | '/posts/$postId'
    | '/'
    | '/profile'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/create_post'
    | '/search'
    | '/settings'
    | '/posts/$postId'
    | '/'
    | '/profile'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/_quest'
    | '/_auth/_layout'
    | '/_quest/auth'
    | '/_auth/_layout/create_post'
    | '/_auth/_layout/search'
    | '/_auth/_layout/settings'
    | '/_auth/posts/$postId'
    | '/_auth/_layout/'
    | '/_auth/_layout/profile/'
    | '/_auth/_layout/profile/$userId/followers'
    | '/_auth/_layout/profile/$userId/following'
    | '/_auth/_layout/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  QuestRoute: typeof QuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_quest': {
      id: '/_quest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof QuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_quest/auth': {
      id: '/_quest/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof QuestAuthRouteImport
      parentRoute: typeof QuestRoute
    }
    '/_auth/_layout': {
      id: '/_auth/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout/': {
      id: '/_auth/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/posts/$postId': {
      id: '/_auth/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthPostsPostIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_layout/settings': {
      id: '/_auth/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthLayoutSettingsRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/search': {
      id: '/_auth/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthLayoutSearchRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/create_post': {
      id: '/_auth/_layout/create_post'
      path: '/create_post'
      fullPath: '/create_post'
      preLoaderRoute: typeof AuthLayoutCreate_postRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/profile/': {
      id: '/_auth/_layout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthLayoutProfileIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/profile/$userId/': {
      id: '/_auth/_layout/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthLayoutProfileUserIdIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/profile/$userId/following': {
      id: '/_auth/_layout/profile/$userId/following'
      path: '/profile/$userId/following'
      fullPath: '/profile/$userId/following'
      preLoaderRoute: typeof AuthLayoutProfileUserIdFollowingRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/_layout/profile/$userId/followers': {
      id: '/_auth/_layout/profile/$userId/followers'
      path: '/profile/$userId/followers'
      fullPath: '/profile/$userId/followers'
      preLoaderRoute: typeof AuthLayoutProfileUserIdFollowersRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutCreate_postRoute: typeof AuthLayoutCreate_postRoute
  AuthLayoutSearchRoute: typeof AuthLayoutSearchRoute
  AuthLayoutSettingsRoute: typeof AuthLayoutSettingsRoute
  AuthLayoutIndexRoute: typeof AuthLayoutIndexRoute
  AuthLayoutProfileIndexRoute: typeof AuthLayoutProfileIndexRoute
  AuthLayoutProfileUserIdFollowersRoute: typeof AuthLayoutProfileUserIdFollowersRoute
  AuthLayoutProfileUserIdFollowingRoute: typeof AuthLayoutProfileUserIdFollowingRoute
  AuthLayoutProfileUserIdIndexRoute: typeof AuthLayoutProfileUserIdIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutCreate_postRoute: AuthLayoutCreate_postRoute,
  AuthLayoutSearchRoute: AuthLayoutSearchRoute,
  AuthLayoutSettingsRoute: AuthLayoutSettingsRoute,
  AuthLayoutIndexRoute: AuthLayoutIndexRoute,
  AuthLayoutProfileIndexRoute: AuthLayoutProfileIndexRoute,
  AuthLayoutProfileUserIdFollowersRoute: AuthLayoutProfileUserIdFollowersRoute,
  AuthLayoutProfileUserIdFollowingRoute: AuthLayoutProfileUserIdFollowingRoute,
  AuthLayoutProfileUserIdIndexRoute: AuthLayoutProfileUserIdIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AuthPostsPostIdRoute: typeof AuthPostsPostIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthPostsPostIdRoute: AuthPostsPostIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface QuestRouteChildren {
  QuestAuthRoute: typeof QuestAuthRoute
}

const QuestRouteChildren: QuestRouteChildren = {
  QuestAuthRoute: QuestAuthRoute,
}

const QuestRouteWithChildren = QuestRoute._addFileChildren(QuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  QuestRoute: QuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
