/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutFollowingRouteImport } from './routes/_layout/following'
import { Route as LayoutFollowersRouteImport } from './routes/_layout/followers'
import { Route as LayoutProfileIndexRouteImport } from './routes/_layout/profile/index'
import { Route as LayoutPostsPostIdRouteImport } from './routes/_layout/posts/$postId'
import { Route as LayoutCommentsPostIdRouteImport } from './routes/_layout/comments/$postId'

const AboutLazyRouteImport = createFileRoute('/about')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFollowingRoute = LayoutFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFollowersRoute = LayoutFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostsPostIdRoute = LayoutPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCommentsPostIdRoute = LayoutCommentsPostIdRouteImport.update({
  id: '/comments/$postId',
  path: '/comments/$postId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/about': typeof AboutLazyRoute
  '/followers': typeof LayoutFollowersRoute
  '/following': typeof LayoutFollowingRoute
  '/': typeof LayoutIndexRoute
  '/comments/$postId': typeof LayoutCommentsPostIdRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/profile': typeof LayoutProfileIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof AboutLazyRoute
  '/followers': typeof LayoutFollowersRoute
  '/following': typeof LayoutFollowingRoute
  '/': typeof LayoutIndexRoute
  '/comments/$postId': typeof LayoutCommentsPostIdRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/profile': typeof LayoutProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/about': typeof AboutLazyRoute
  '/_layout/followers': typeof LayoutFollowersRoute
  '/_layout/following': typeof LayoutFollowingRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/comments/$postId': typeof LayoutCommentsPostIdRoute
  '/_layout/posts/$postId': typeof LayoutPostsPostIdRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/about'
    | '/followers'
    | '/following'
    | '/'
    | '/comments/$postId'
    | '/posts/$postId'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/followers'
    | '/following'
    | '/'
    | '/comments/$postId'
    | '/posts/$postId'
    | '/profile'
  id:
    | '__root__'
    | '/_layout'
    | '/auth'
    | '/about'
    | '/_layout/followers'
    | '/_layout/following'
    | '/_layout/'
    | '/_layout/comments/$postId'
    | '/_layout/posts/$postId'
    | '/_layout/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/following': {
      id: '/_layout/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof LayoutFollowingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/followers': {
      id: '/_layout/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof LayoutFollowersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/posts/$postId': {
      id: '/_layout/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutPostsPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/comments/$postId': {
      id: '/_layout/comments/$postId'
      path: '/comments/$postId'
      fullPath: '/comments/$postId'
      preLoaderRoute: typeof LayoutCommentsPostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutFollowersRoute: typeof LayoutFollowersRoute
  LayoutFollowingRoute: typeof LayoutFollowingRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutCommentsPostIdRoute: typeof LayoutCommentsPostIdRoute
  LayoutPostsPostIdRoute: typeof LayoutPostsPostIdRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFollowersRoute: LayoutFollowersRoute,
  LayoutFollowingRoute: LayoutFollowingRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutCommentsPostIdRoute: LayoutCommentsPostIdRoute,
  LayoutPostsPostIdRoute: LayoutPostsPostIdRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  AboutLazyRoute: AboutLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
